### ISSUE TITLE
eml_validate: message or data.frame?

### ISSUE THREAD

**Issue by masalmon** [ropensci/EML#161] opened 2016-06-20 11:26 UTC
I'm currently using messages from `eml_validate` to correct my eml creating code.

I wonder whether it'd be easier to have `eml_validate` output as a list:

* one element would be the logical currently returned by the function

* the other one would be a data.frame with 3 columns (error$line, error$col, error$msg) that the user could e.g. save in an Excel file and use as a reference.

I have quite a few messages to deal with, maybe other users only get three lines from `eml_validate` and therefore wouldn't care about message vs. output. :smile_cat:

**Comment by cboettig** [comment] 2016-06-20 14:41
@masalmon Thanks for suggestion, I know debugging with `eml_validate` can be pretty annoying. iirc, it's made worse because `eml_validate` only stops on the first error it finds(?).  

 I'm not sure if line and col references would help most people though -- that would refer to positions in the XML text, and then you still have to figure out what R object is invalid and re-create it.  As you probably saw, `eml_validate` is just a call to the `libxml2` validator, so hard to make it smarter directly.  (Other validators might already do a nicer job, but we don't have them as open source C libs!)

I think it would be better if we could catch common validation errors at the time of creating the relevant R object (see #148).  S4 classes can run their own validation steps.  I don't think it's worth trying to be 100% valid this way, I think `eml_validate` against the schema itself is always the definitive check, but I think we could add a few validation checks just to catch common mistakes like missing required fields.

Thus it would be super helpful to know what validation errors you've seen so far, and we can see if there's a way to flag those at the R level.

**Comment by cgries** [comment] 2016-06-20 15:05
@cboettig  One error message I got was for not entering minimum and maximum values. Those are not required elements, yet you are putting them into the EML. (- I know, it's good practice ...) It probably would be better to check if there are values available and if not don't add those elements.

**Comment by cboettig** [comment] 2016-06-20 18:00
@cgries yeah, that sounds like a bug -- can you paste in a minimal code example so I can reproduce that?  (For instance -- in the creating EML vignette, I added an example with a numeric field that doesn't declare max and min, and I do not see such an error).

**Comment by cgries** [comment] 2016-06-20 18:23
@cboettig this is what I get when I don't provide min and max for a numeric column:

`> eml_validate(eml)
208.0: Element 'minimum': '' is not a valid value of the atomic type 'xs:float'.

209.0: Element 'maximum': '' is not a valid value of the atomic type 'xs:float'.`

I interpret this that the code puts character null in, which is not a float - I assume. 

It all works if I provide the columns minimum and maximum in the attribute metadata data frame with the correct numbers or dates.

here is what I do to make this work:
`df <- read.csv("Mendota2014.csv", header=TRUE, sep=",", quote("\""))
str(df)

#convert dates to date type
df$sampledate<-as.Date(df$sampledate, format="%Y-%m-%d")
str(df)

#set up the data frame for metadata
rows <- ncol(df)
attributes <- data.frame(attributeName = character(rows), 
                         formatString = character(rows), 
                         unit = character(rows), 
                         numberType = character(rows), 
                         definition = character(rows), 
                         attributeDefinition = character(rows),
                         columnClasses = character(rows),
                         maximum = character(rows),
                         minimum = character(rows),
                         stringsAsFactors = FALSE)

#get some metadata from data frame
attributes$attributeName <- names(df)

#get minimums and maximums for number columns
#these functions actually produce lists that are being forced into the dataframe
maxima <- list()
maxima[1] <- as.character(max(df$sampledate))
maxima[2:7] <- as.character(sapply(df[c(2,3,4,5,6,7)], max, na.rm = TRUE))
maxima[8] <- ""

attributes$maximum <- maxima

minima <- list()
minima[1] <- as.character(min(df$sampledate))
minima[2:7] <- as.character(sapply(df[c(2,3,4,5,6,7)], min, na.rm = TRUE))
minima[8] <- ""

attributes$minimum <- minima

attributes$columnClasses <- sapply(df, class)
#set what R thinks is integer to numeric
attributes$columnClasses[attributes$columnClasses == "integer"] <- "numeric"

#convert this mish mash of lists and data frame back to a character data frame for output
attributes <- data.frame(lapply(attributes, as.character), stringsAsFactors=FALSE)

edit(attributes)
write.csv(attributes, file = "mendota2014Metadata2.csv", row.names = FALSE)
`

**Comment by cboettig** [comment] 2016-06-20 19:30
@cgries thanks! looks like I had a bug that wasn't allowing you to have some numeric data with bounds and other without bounds.  (Your error comes from the XML creating a a blank node from `minimum` instead of omitting that element when no value was available)

Should be fixed now.

**Comment by cgries** [comment] 2016-06-20 20:39
great thanks!

**Comment by masalmon** [comment] 2016-06-21 08:15
Some errors I got:

* I had not given a role to someone in `associatedParty`. Maybe this could be checked when creating the `associatedParty`? I don't even know which parts of it are compulsory (name, role, contact information?)

* I had not written a packageID. Should there be an error when using `new("eml", blabla)` without packageID and system?

* When I create tables where there are custom units, I get a warning -> maybe there could be a similar warning if one creates an eml in `new` with a dataset containing tables with custom units, without adding an unitLists? Maybe even checking that the custom units all have a line a in `unitList`?

This is in line with your S4 validation ideas.

**Comment by masalmon** [comment] 2016-06-21 08:20
BTW, should minimum/maximum be:

* the range of values in the data

* the range of possible values with the device used?

**Comment by mbjones** [comment] 2016-06-21 08:32
Min and max represent the domain of possible values (not the range).

Matt

**Comment by masalmon** [comment] 2016-06-22 11:40
I had forgotten a `numberType` in my Excel file, which made me think that maybe `set_attributes` could give a warning/ an error when one has a numericDomain attribute without numberType? 

More generally, I'd be happy to help add the warnings.

**Comment by cboettig** [comment] 2016-06-22 14:35
Great idea. Yeah, I think warnings for missing required types would be better than S4 validation route in this case.  And PRs more than welcome!

**Comment by masalmon** [comment] 2016-06-22 14:41
Cool, I'll try to contribute in the next weeks (but not next week). Should this be a message, a warning, an error? I think warnings are better.

**Comment by cboettig** [comment] 2016-06-22 14:51
Right, I agree a warning is better for validation issues (doesn't break scripts as much, and it is possible to address validation issues by modifying s4 slots after the fact anyway rather than starting from square 1).

**Comment by masalmon** [comment] 2016-06-23 11:46
Regarding the validation of an `eml` itself before its creation, I guess this is something that would need to be done in the create_package/ code which I don't understand well enough yet. 

A less elegant solution would be to add pre-checks in `eml_validate`. Or do you plan to have a `set_eml` function that work like say `set_unitList`? Such a function could include checks before a call to `new`.

**Comment by cgries** [comment] 2016-06-23 14:28
@masalmon After figuring out how to define a custom unit in my code I got confused when I continued to get the warning message in `set_attribute` about that custom unit I was using in the data frame for defining attributes. Although in the end the EML validated just fine. It would be great if the code could check for that custom unit definition at the point of using `set_attribute` rather than at the end during validation. - Just a thought.

**Comment by masalmon** [comment] 2016-06-23 14:34
@cgries I was more confused by the suggestion to use another unit, because I have not chosen the units of the measurements :smile: 

More seriously, though, @cboettig, would it be a good idea to add an `unitLists` argument to `set_attributes` so that the units in `attributes` would be checked against standard units but also the custom units already defined?

**Comment by cboettig** [comment] 2016-06-23 16:45
@cgries @masalmon Thanks! Good point, sounds like `set_attribute()` should have an optional slot for `unitList` so that it does not warn if given custom units that have been properly defined.

Also definitely open to suggestions about how to word warning and error messages -- you both capture the user perspective better than I and can probably suggest more intelligent messages.  


@masalmon re validation more generally, I'm not entirely sure I follow what you mean, but here's my thinking currently:

- Lowest level: EML package should automatically do the right thing when possible.  For instance, EML schema is picky about the order of child elements even when that order is more aesthetic than semantic (e.g. `creator` and `title` must come before `dataTable` in a `dataset` element) -- so for these, element order is hardwired into the class definitions to minimize validation errors. This level is mostly already implemented.

- Required vs optional elements.  I think this is a big one, and this seems to be the main source of validation errors in all of your (very helpful!) examples.  We could hard-wire this into the S4 class validation methods, and maybe that makes sense at least some of the time, but that would commit us to having `ERROR` instead of `WARNING`.  So, I think the better way to do these for the most part is in the `set_` methods (even though those exist for only a small subset of the most common / crucial elements).  Alternatively, there maybe some clever thing we can do in S4 to get warning messages instead of error messages.  

- Final validation: ultimately eml_validate() must be used to really check schema validation.  Giving a flexible user interface where elements can be built piecemeal probably means that it will always be possible to create invalid EML. (And of course there are many errors that aren't either missing required slots or slot order, but I think those are most common).  

Maybe there's a need for a strategy to address some other class of validation errors as well before getting to `eml_validate()`, but that's my thinking so far.  (I guess the example with custom units is such a special case. I'm not 100% sure if `eml_validate()` / schema validation checks that no unit has been used without being defined or standard; guess it would be quick to experiment).

**Comment by cboettig** [comment] 2016-06-23 17:16
@masalmon Ah, so if we want `new("element")` to warn instead of error whenever it is called but omits a required element, I think the most comprehensive way to do that would be to just add those checks to the `initialize` method for the class.

I create these programmatically from the schema files themselves, since there are so many classes.  The class and methods files are created using the scripts in `inst/create-package`, https://github.com/ropensci/EML/blob/master/inst/create-package/create_package.R .  Currently the `initialize` methods are defined just to attain nice behavior around repeated slots (`ListOf` classes). Ideally one would pull out which slots were and were not required when parsing the schema, and then write an automatic check for that in declaring these.  But that's probably a pretty involved undertaking.

**Comment by cboettig** [comment] 2016-06-23 21:37
Okay, perhaps this is better than modifying `initialize` in that at least it is more natural: you can make S4 validation not throw an error simply by making sure the validity function returns TRUE always:

```{r
setClass("testclass", 
               slots = c(A = "character", B = "character"), 
               validity = function(object){ 
                 if(length(object@B) < 1)  
                   warning("B is required")
                 TRUE
               })
```

Without the trailing TRUE `new("testclass", A = "stuff")` would throw an error, but with it, it only throws a warning.  And failing the type checking still throws an error: `new("testclass", A = 4)`.  

However the `setClass` commands are also written programmatically from `create-package.R, so the classes (the files classes.R and methods.R) should not be edited by hand...

**Comment by masalmon** [comment] 2016-06-24 05:44
But would it be possible to change the code that creates the commands so that it also takes into account which fields are required? However it might not be easy to also check the permitted values of each field, which would be important as well: is there a good list of class+fields + whether they are required + whether their values are limited?

**Comment by cboettig** [comment] 2016-06-24 17:26
@masalmon In principle this is possible -- all of this information is contained in a machine-readable format in the XSD files which define the schema.  It's precisely those documents that allow the validator to know what is and isn't required, and what values are and are not acceptable, etc.  

Unfortunately, doing this isn't trivial.  I'm not an expert in XSD, though it's reasonably logical.  For instance, here's the part that says the column for specifying the `precision` on a numeric unit is optional: https://github.com/ropensci/EML/blob/master/inst/xsd/eml-attribute.xsd#L469 (`minOccurs="0"`).  Note that the type is also defined, etc.  Everything is in the schema.  

Here's my script that reads these files and identifies every defined element and creates an S4 class for it: https://github.com/ropensci/EML/blob/master/inst/create-package/create_classes.R  It's not pretty -- S4 does a few things differently from XML schema -- for instance, in XML schema a complexType definition can be referred to before it is defined, but not so S4.  (Ultimately S4 might not be the right choice; and maybe the new R6 and xml2 packages could offer a better strategy, but starting from scratch might be more painful).   Having R code write R code is quite powerful but tricky too. 

We could instead just manually add validation functions to classes where it is most important, i.e. by adding a new validated-classes.R file in `R` that redefines the key classes with validators included. Lemme know what you think.

**Comment by masalmon** [comment] 2016-06-24 18:33
I'm not an expert in XSD either 😀 I hear you on starting from scratch! Unless we get help from a xml2 expert.

How would you select the ''most important' ones? Sounds like a good strategy especially if the other classes are used by people who know their way around EML anyway.

**Comment by cboettig** [comment] 2016-06-24 18:46
Well for a first pass, I'd say the 'most important' ones are the ones where it's been worth defining a `set_` method for (`coverage`, `physical`, `attributes`) and the big container classes like `dataset` & `dataTable` (and probably the other high-level structures `spatialRaster`/`spatialVector` etc, but I'm less familiar with them.  

(even the `xml2` devs don't seem particularly interested in working with schemas -- at this time they won't even consider validating an XML file against a schema, https://github.com/hadley/xml2/issues/31.  At the other extreme, Duncan has the XMLSchema package on omegahat, which can parse XSD and generate S4 classes automatically, but it's not really up to the task for a schema as big as EML).

**Comment by cboettig** [comment] 2016-10-13 21:49
Closing.  `eml_validate` now returns messages on invalid lines, and returns the status code TRUE or FALSE for automated checks.  Good suggestions in this thread for using S4 validation at particular spots, which should be filed as a separate issue for the main `set_` methods.

**Closed by cboettig** 2016-10-13 21:49 UTC
