### ISSUE TITLE
recommend unf for authentication?

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#239] opened 2018-04-04 10:36 UTC
https://github.com/leeper/UNF

**Comment by amoeba** [comment] 2018-04-05 01:18
This is cool. I guess I'd seen it before but not thought of this angle. 

I see that `authentication` in EML is currently defined as:

> This element describes authentication procedures or techniques, typically by giving a checksum value for the object. The method used to compute the authentication value (e.g., MD5) is listed in the method attribute.
> Example(s):
> f5b2177ea03aea73de12da81f896fe40

Where the `method` attribute is defined as:

> This element names the method used to calculate and authentication checksum that can be used to validate a bytestream. Typical checksum methods include MD5 and CRC.
>Example(s):
>MD5

I think UNF fits into the existing schema both in spirit and in practice.

`physical`, the section of EML in which `authentication` is defined, is described as:

> The eml-physical module describes the external and internal physical characteristics of a data object as well as the information required for its distribution. Examples of the external physical characteristics of a data object would be the filename, size, compression, encoding methods, and authentication of a file or byte stream.

I'm not sure whether I feel like UNF would be *preferred* over checksums. The `physical` section also describes the distribution metadata for an entity and checksums are often a key part of verifying an entity has been correctly transferred over the wire. Are people using UNF's in practice? They sound super cool.

**Comment by mbjones** [comment] 2018-04-05 03:12
Definitely useful. And I agree with @amoeba that it would be a form of authentication checksum.  However, before I used it broadly I'd want to be sure it was compatibly implemented in multiple common languages. It's also not clear to me how much we really gain over checksums, although the format independence is a neat feature.  The floating point rounding seems like an anti-feature to me, although I don't understand it fully.

**Comment by maelle** [comment] 2018-04-05 04:58
Thanks for your answers! Yeah I threw it here and don't know much about it, the advantages described in the README seemed interesting (in particular 3, "UNFs detect misinterpretation of the data by statistical software" and 4, "UNFs are strongly tamper resistant. Any accidental or intentional changes to data values will change the resulting UNF. Most file checksums and descriptive statistics detect only certain types of changes.") but I'm not an expert at all! 😇  I'll make a note to try and find out how widely used UNF's are!

**Comment by amoeba** [comment] 2018-04-05 05:13
> Most file checksums and descriptive statistics detect only certain types of changes.

I wonder what they mean there. I thought checksums were perfectly tamper-resistant. And different files can have the same UNF by design.

**Comment by maelle** [comment] 2018-04-05 05:55
Googling "UNF dataverse" didn't bring much so let me ask the expert. @leeper, I've recently discovered your UNF package thanks to an issue in another repo. Here are two questions for you if you have time:

* How widely used are UNF's in your experience? Is it a social science thing?

* Do you consider them better than say md5 checksums for tabular data?

Thank you!

**Comment by leeper** [comment] 2018-04-05 06:42
- My sense is UNF is not widely used - Dataverse is the only major application I've seen.
 - Yes, they are supposed to be better than md5 because a UNF is format-independent. Example: an md5 for a CSV versus a TSV of identical data will be different - the UNF will be the same because it creates the hash in-memory based on the values of the data rather than the structure of the file. (side note: I inherited this package from someone else so the point about tampering is a legacy - not sure exactly what that was meant to refer to.)

**Comment by maelle** [comment] 2018-04-05 07:38
Thanks @leeper !

**Closed** 2018-11-27 19:57 UTC
