### ISSUE TITLE
viewing EML interactively (e.g. via htmlwidget / listviewer)

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#189] opened 2017-01-17 15:53 UTC
I don't know whether it's worth mentioning in the doc somewhere but using `jsonedit` from the [`listviewer` package](https://github.com/timelyportfolio/listviewer) for looking at the xml is quite handy IMO (after transforming the eml to a list)

**Comment by masalmon** [comment] 2017-01-17 15:56
Adding a screenshot:

![listviewer](https://cloud.githubusercontent.com/assets/8360597/22027973/d9897906-dcd5-11e6-9fa7-137fde3cebe6.png)

**Comment by masalmon** [comment] 2017-01-17 16:25
Note that it's not perfect but much better than looking at the xml :-)

**Comment by cboettig** [comment] 2017-01-17 20:32
Nice.  We should probably add an example of this in the "Reading EML" vignette

**Comment by amoeba** [comment] 2017-01-17 20:42
I think this is really useful. Is this useful enough to write something like an `eml_view` function that renders this? `listviewer` could be brought in as a `Suggests` and the function could fail gracefully if `listviewer` isn't installed.

**Comment by cboettig** [comment] 2017-01-17 20:49
Yeah, I was pondering that too; like you hint at `listviewer` would bring in quite a lot of dependencies.  I've used the `Suggests` trick before (`ggplot2` and other Hadley packages do this too) though I think it's a bit of a hack of the `Suggests` usage; iirc one has to be a bit fancy about how to do this since CRAN will reject having a function in `R/` that calls a function from a package not in Imports/Depends.  Definitely open to a PR for it.

**Comment by masalmon** [comment] 2017-01-18 10:20
Thanks both for your enthusiasm. Sooo turns out it's not always pretty with the EML of the package instead of mine. I had to use

```r
XML::xmlToList(eml_list,
                         addAttributes = FALSE,
                          simplify = FALSE)
```
instead of `addAttributes = TRUE` because when the EML is transformed to a list some elements are lists with named and not named elements which `listviewer::jsonedit` doesn't like. I'll make a PR in a minute though, so you can try it out. Because of this `addAttributes` the highest levels don't have names, but I think it's easier this way than finding all sub-lists with both named and not named elements and do something about them. For my own EML it still looks useful (compared to the effort invested in getting the view).

The function returns `NULL` if `listviewer` isn't installed and a message. I've uninstalled `listviewer` to make sure it works :grin: For another package I contribute to we have a similar thing except the package function returns an error, but our excuse was not having too many dependencies but rather that the package we call, INLA, is not on CRAN.

**Comment by amoeba** [comment] 2017-01-18 19:25
Ah, that's very tricky. Good catch and nice work!

Out of curiosity, have you tried out the XML-to-list feature in the `xml2` package?

```{r}
doc <- xml2::read_xml(eml_path)
jsonedit(xml2::as_list(doc))
```

It seems to produce different output than the similar feature in the `XML` package which results in a different result in the `listviewer::jsonedit` Viewer pane. I see pros and cons to each approach. Screenshots included:

**Using XML::xmlToList**

![image](https://cloud.githubusercontent.com/assets/563/22079432/4ad86fc6-dd68-11e6-918d-8773848b7a91.png)




**Using xml2::as_list**
![image](https://cloud.githubusercontent.com/assets/563/22079437/4d55c05a-dd68-11e6-9988-5f1a51d22e44.png)


Any thoughts or predilections?

**Comment by cboettig** [comment] 2017-01-18 20:41
@amoeba Interesting.  I've been thinking about migrating the whole package to `xml2` now that we have write support there; not sure how hard it would be; might improve the performance.  Meanwhile just pulling in `xml2` as a Suggest for `listviewer` could be viable.

**Comment by amoeba** [comment] 2017-01-18 20:44
Ah yes, I wasn't thinking about package deps. I think the solution @masalmon wrote up is not necessarily better or worse than a solution using so maybe it makes sense to use the `XML`-based version now and switch to an `xml2`-based solution later, after the `XML` dep has been removed.

**Comment by masalmon** [comment] 2017-01-18 21:49
Oh interesting to see the difference! Let's use XML for now, ok for switching later but maybe we'll also have a fancy specific function for an even nicer view of EML by then 😉

**Comment by cboettig** [comment] 2017-03-15 03:17
Trying to migrate everything to xml2, I have listviewer tests failing on some of the tests with: 

```r
listviewer::jsonedit(eml_list)
Error in FUN(X[[i]], ...) : 
  'options' must be a fully named list, or have no names (NULL)
```

any ideas?

**Comment by amoeba** [comment] 2017-03-15 07:21
Real bizarre. I took a bit of a walk in the woods and found this out. Here's a minimum reproducible example:




```{R}
doc <- xml2::read_xml(system.file("xsd/test/eml-datasetWithUnits.xml", package = "EML"))
docl <- xml2::as_list(doc)
listdata <- listviewer:::list_proper_form(docl)

x <- list(
  data = listdata,
  options = list(mode = 'tree', 
                 modes = c('code', 'form', 'text', 'tree', 'view'))
)

structure(list(x = x, 
               width = NULL,
               height = NULL, 
               sizingPolicy = NULL, 
               dependencies = NULL, 
               elementId = NULL, 
               preRenderHook = NULL, 
               jsHooks = list()),
          class = c("jsonedit", "htmlwidget"), 
          package = 'listviewer')
```

If you run that and use the RStudio interactive debugger you find out what's likely the proximate cause of the error:

<img width="640" alt="screen shot 2017-03-14 at 11 09 54 pm" src="https://cloud.githubusercontent.com/assets/563/23937284/864ef218-090b-11e7-88b2-04fe0ee4b904.png">

The first element if the list `options` is indeed unnamed. Then I took a look at the PNG and the XML and made a guess that it's the XML comment in the stmml definition at the bottom of the document. Removing it and re-running the above code against the modified XML doc worked with no errors. And _with that figured out_, a fix for this document of:

```{R}
doc <- xml2::read_xml(system.file("xsd/test/eml-datasetWithUnits.xml", package = "EML"))
docl <- xml2::as_list(doc)
docl[["additionalMetadata"]][["metadata"]][["unitList"]] <- docl[["additionalMetadata"]][["metadata"]][["unitList"]][-which(names(docl[["additionalMetadata"]][["metadata"]][["unitList"]]) == "")]
listviewer::jsonedit(docl)
```

fixes up the `xml2::as_list`'ed output so it works. 🤷‍♂️ 

I am wondering now if any XML comments in the document cause this and if this routine would have to filter them out or if this is a good thing to PR `listviewer` or `xml2` about since it should apply to all XML.

**Comment by maelle** [comment] 2017-03-15 07:24
Mmmh and we can't cover all unnamed cases

I meant to have a look at https://github.com/hrbrmstr/xmlview will do, maybe easier to use although less pretty I think

**Comment by amoeba** [comment] 2017-03-15 07:42
Well don't have to love the code we right if it works:

```{R}
doc_path <- system.file("xsd/test/eml-datasetWithUnits.xml", package = "EML")
lns <- readLines(doc_path)
lns <- stringr::str_replace_all(lns, "<!--.*-->", "")
out_path <- tempfile()
writeLines(lns, out_path)
doc <- xml2::read_xml(out_path)
docl <- xml2::as_list(doc)
listviewer::jsonedit(docl)
```

**Comment by maelle** [comment] 2017-03-15 07:56
True and nice fix :-)

I'm installing `xmlview` for being able to compare the output

**Comment by maelle** [comment] 2017-03-15 08:15
So `xmlview` can help you see the whole xml in different styles which is nice. But I couldn't get the collapsable version, `xml_view::xml_tree_view` to work which makes it less handy I think? Could one of you tell me if `xml_view::xml_tree_view` is collapsable for you? Because if it is _maybe_ that's a better option (no need to convert to list first for instance)

**Comment by amoeba** [comment] 2017-03-15 15:10
`xmlview::xml_tree_view(doc)` produced a collapsible version for me. I noticed I had to click on the `+` and `-` text and not on the element name as I expected to get collapsing working. That's easy enough to fix. I'm still a bit partial to the `listviewer` version but this certainly works.

**Comment by maelle** [comment] 2017-03-15 15:14
Oooh now I see how it works thanks @amoeba 🙈 

If you prefer `listviewer` I'm happy with your fix.

**Comment by amoeba** [comment] 2017-03-15 15:17
Sounds good. I'll let this sit for a bit so others can comment as xmlview is a nice alternative. If others prefer to stay with listview I'll PR. In the PR I'll tweak the code so it's cleaner and faster.

**Comment by maelle** [comment] 2017-07-13 10:32
@cboettig currently the function doesn't work because of the commented part, right?

**Comment by cboettig** [comment] 2017-07-13 18:56
Tested uncommenting it and seems like the current function has deeper issues now... see #222

**Comment by cboettig** [comment] 2018-11-27 20:42
No native eml_view option, but I think this is much easier now that EML is just a list object in R, and can use the built-in explorer in RStudio, e.g.  `View(eml)`

**Closed by cboettig** 2018-11-27 20:42 UTC
